[governance]
slug = "sbr"
name = "Saber"
address = "9tnpMysuibKx6SatcH3CWR9ZsSRMBNeBf1mhfL6gAXR4"
description = "AMM for mean-reverting trading pairs on Solana"
iconURL = "https://spl-token-icons.static-assets.ship.capital/icons/101/Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1.svg"

[governance.token]
address = "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1"
name = "Saber Protocol Token"
symbol = "SBR"
decimals = 6
logoURI = "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1/logo.svg"

[governance.token.extensions]
coingeckoId = "saber"
discord = "https://chat.saber.so"
github = "https://github.com/saber-hq"
medium = "https://blog.saber.so"
twitter = "https://twitter.com/saber_hq"
website = "https://saber.so"
