[governance]
network = "mainnet-beta"
slug = "sunny"
name = "Sunny Aggregator"
address = "8NDDbatDi5WxB433q3qyMMMYvjodMkCenGdTjkxuASyE"
description = "Solana's cross-chain DeFi yield aggregator."

[governance.token]
address = "SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag"

[links]
website = "https://sunny.ag"
app = "https://app.sunny.ag"
forum = "https://github.com/SunnyAggregator/forum/discussions/"
discord = "https://chat.sunny.ag/"
github = "https://github.com/SunnyAggregator"
medium = "https://medium.com/sunny-aggregator"
twitter = "https://twitter.com/SunnyAggregator"

[quarry]
rewarder = "97PmYbGpSHSrKrUkQX793mjpA2EA9rrQKkHsQuvenU44"

[quarry.gauge]
gaugemeister = "GBYZGgJks1re9BkJ8RB5QUMmmoyb7MsQ9ABFrgX5c5GZ"

[proposals]
notice = """\
To create a proposal, first create a proposal on the [Sunny Aggregator Governance GitHub repository](https://github.com/SunnyAggregator/governance/issues/new?assignees=&labels=proposal&template=governance-proposal.md&title=%5BPROPOSAL%5D).

Once you have determined that there is sufficient community support,
add the link to the GitHub issue and create a proposal.
"""
discussion = { required = true, link = "https://github.com/SunnyAggregator/governance/labels/proposal", prefix = "https://github.com/SunnyAggregator/governance/issues/" }
