[governance]
network = "mainnet-beta"
slug = "sbr"
name = "Saber"
address = "9tnpMysuibKx6SatcH3CWR9ZsSRMBNeBf1mhfL6gAXR4"
description = "AMM for mean-reverting trading pairs on Solana"

[governance.token]
address = "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1"

[governance.parameters.governor]
quorum-votes = 400_000_000_000000
token-mint = "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1"
voting-delay = 86_400
voting-period = 259_200
timelock-delay = 86_400

[governance.parameters.locker]
max-stake-vote-multiplier = 10
min-stake-duration = 604_800 # 7 days
max-stake-duration = 157_680_000 # 5 years
proposal-activation-min-votes = 10_000_000_000000 # 10M veSBR / 1M SBR
whitelist-enabled = true

[site]
aliases = ["dao.saber.so"]

# DAO addresses to track.
[addresses]
governor = "9tnpMysuibKx6SatcH3CWR9ZsSRMBNeBf1mhfL6gAXR4"
electorate = "4tr9CDSgZRLYPGdcsm9PztaGSfJtX5CEmqDbEbvCTX2G"

[addresses.smart-wallet]
label = "Smart Wallet"
type = "smart-wallet"
address = "F9TxY3Bj1tWebTHZPJC323WK8KwAe3W6XKkg2hzCdsKM"

[addresses.executive-council]
label = "Executive Council"
type = "smart-wallet"
address = "ByB3GkPHuUBmzcNbY1Ed7xK2uMkEkNsxTwjMGAFeLsbw"

[addresses.emergency-dao]
label = "Emergency DAO"
type = "smart-wallet"
address = "F9TxY3Bj1tWebTHZPJC323WK8KwAe3W6XKkg2hzCdsKM"

[proposals]
notice = """\
To create a proposal, first make a post on the [Saber Governance Forum](https://github.com/saber-hq/governance/labels/proposal).

Once you have determined that there is sufficient community support,
add the link to the discussion thread and create a proposal.
"""
discussion = { required = true, link = "https://github.com/saber-hq/governance/labels/proposal", prefix = "https://github.com/saber-hq/governance/issues/" }

[links]
website = "https://saber.so"
app = "https://app.saber.so"
forum = "https://github.com/saber-hq/governance/discussions/"
discord = "https://chat.saber.so"
github = "https://github.com/saber-hq"
medium = "https://blog.saber.so"
twitter = "https://twitter.com/saber_hq"

[quarry]
rewarder = "rXhAofQCT7NN9TUqigyEAUzV1uLL4boeD8CRkNBSkYk"
mint-wrapper = "EVVDA3ZiAjTizemLGXNUN3gb6cffQFEYkFjFZokPmUPz"
redeemer = "CL9wkGFT3SZRRNa9dgaovuRV7jrVVigBUZ6DjcgySsCU"
features = ["issue-tokens"]
# other rewarders managed (or jointly managed) by the Saber team
additional-rewarders = [
    "2UsGfm8S36eW58U4JeKgVC9fcXsqf7D6vfm4GHUtnENn",
    "CXer5v3osVQFDWUB3SJUPB1PN1dB3dQSQfymyAnmCryp",
    "Wz2Zzi5BHmYr75yNzJG8NZ8U1T9cSWKf6ATRwZF7qV6",
    "9eNj2Y4YdqM9Unw8qTm8kzx1Xt64Rft8a6HjvpkPL7QJ"
]

[quarry.operator]
address = "GdW7Accmjusk8qKUPoCMJasEje63h97igqkjdEpacpRN"
features = ["set-annual-rewards-rate"]

[quarry.gauge]
gaugemeister = "28ZDtf6d2wsYhBvabTxUHTRT6MDxqjmqR7RMCp348tyU"
